# Generated by Django 4.2.4 on 2023-08-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cep_endereco', models.CharField(max_length=10, verbose_name='CEP')),
                ('estado_endereco', models.CharField(max_length=4, verbose_name='Estado')),
                ('cidade_endereco', models.CharField(max_length=30, verbose_name='Cidade')),
                ('bairro_endereco', models.CharField(max_length=30, verbose_name='Bairro')),
                ('endereco_endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numero_endereco', models.CharField(max_length=10, verbose_name='Número Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('data_de_registro', models.DateField(auto_now_add=True)),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.administrador')),
            ],
        ),
    ]
